---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nagrestconf-envvars
data:
  NAGCTL_NAG_DIR: /usr/local/nagios/etc
  NAGCTL_NAG_OBJ_DIR: /usr/local/nagios/etc/objects
  NAGCTL_NAG_CONFIG: /usr/local/nagios/etc/nagios.cfg
  NAGCTL_COMMANDFILE: /usr/local/nagios/var/rw/nagios.cmd
  NAGCTL_NAGIOSBIN: /usr/local/nagios/bin/nagios
  NAGCTL_WWWUSER: www-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-nagrestconf
  labels:
      app: nagrestconf
spec:
  replicas: 1
  selector:
      matchLabels:
          app: nagrestconf
  template:
    metadata:
      labels:
        app: nagrestconf
    spec:
      containers:

      - name: nagios
        image: quantumobject/docker-nagios
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nagios-dir
          mountPath: /usr/local/nagios

      - name: nagrestconf
        image: mclarkson/nagrestconf
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: nagrestconf-envvars
        volumeMounts:
        - name: nagios-dir
          mountPath: /usr/local/nagios
        - name: nagrestconf-tmp-dir # tmp dir is shared with nagrestconf-restarter
          mountPath: /tmp

      - name: nagrestconf-nagios-restarter
        image: mclarkson/nagrestconf-restarter
        volumeMounts:
        - name: nagrestconf-tmp-dir # restarter looks for file written by nagrestconf in /tmp
          mountPath: /tmp
        - name: nagios-dir # just for nagios socket
          mountPath: /usr/local/nagios

      initContainers:

      # Copy data dir to mount
      - name: nagios-one-time-data-copy
        image: quantumobject/docker-nagios
        volumeMounts:
        - name: nagios-dir
          mountPath: /nagios
        command: ['sh', '-c', 'test -e /nagios/bin || cp -a /usr/local/nagios/* /nagios/']

      volumes:
      - name: nagios-dir
        emptyDir: {}
      - name: nagrestconf-tmp-dir
        emptyDir: {}

